Processing  MCIPlus2_Unp-LU4000-du1p9_spin-2-ggON_pT125_M_2000_TuneCP2_py_GEN.root
Wrote local configuration file  cmsRun_cfg_MCIPlus2_Unp-LU4000-du1p9_spin-2-ggON_pT125_M_2000_TuneCP2_py_GEN.root.py
Configuration file Run with the following settings: 
isMC =  True
Pythia GEN
processing  file:/uscms_data/d3/cuperez/CMSSW_9_3_8/src/MCIPlus2_Unp-LU4000-du1p9_spin-2-ggON_pT125_M_2000_TuneCP2_py_GEN.root
Writing output to file  TestMCIPlus2_Unp-LU4000-du1p9_spin-2-ggON_pT125_M_2000_TuneCP2_py_GEN.root
nEventsSample:  1000
Using global tag: 80X_mcRun2_asymptotic_2016_miniAODv2
14-Dec-2018 13:24:52 CST  Initiating request to open file file:/uscms_data/d3/cuperez/CMSSW_9_3_8/src/MCIPlus2_Unp-LU4000-du1p9_spin-2-ggON_pT125_M_2000_TuneCP2_py_GEN.root
----- Begin Fatal Exception 14-Dec-2018 13:24:52 CST-----------------------
An exception of category 'FileOpenError' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing input source of type PoolSource
   [2] Calling RootFileSequenceBase::initTheFile()
   [3] Calling StorageFactory::open()
   [4] Calling File::sysopen()
Exception Message:
Failed to open the file '///uscms_data/d3/cuperez/CMSSW_9_3_8/src/MCIPlus2_Unp-LU4000-du1p9_spin-2-ggON_pT125_M_2000_TuneCP2_py_GEN.root'
   Additional Info:
      [a] Input file file:/uscms_data/d3/cuperez/CMSSW_9_3_8/src/MCIPlus2_Unp-LU4000-du1p9_spin-2-ggON_pT125_M_2000_TuneCP2_py_GEN.root could not be opened.
      [b] open() failed with system error 'No such file or directory' (error code 2)
----- End Fatal Exception -------------------------------------------------
Running  MCIPlus2_Unp-LU4000-du1p9_spin-2-ggON_pT125_M_2000_TuneCP2_py_GEN.root
